<a href="https://colab.research.google.com/github/mcasivaram/Datascience/blob/main/Null_Innovation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NULL Innovation Private Limited**

# **Task:**
# 1. Identify the intent of tweet using ML models.

In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("/content/drive/MyDrive/Tweet_NFT.xlsx - Sheet1.csv")

# Importing the dataset :

In [3]:
df1=pd.DataFrame(data)

In [4]:
df1['tweet_intent'].count()

96364

In [5]:
df1['tweet_intent'].isnull().sum()

31089

In [6]:
df1.head()

id                                         tweet_text  \
0  1212762  @crypto_brody @eCoLoGy1990 @MoonrunnersNFT @It...   
1  1212763  Need Sick Character art❓#art #artist #Artist...   
2  1212765  @The_Hulk_NFT @INagotchiNFT @Tesla @killabears...   
3  1212766  @CryptoBatzNFT @DarekBTW The first project in ...   
4  1212767  @sashadysonn The first project in crypto with ...   

           tweet_created_at  tweet_intent  
0  2022-08-06T16:56:36.000Z     Community  
1  2022-08-06T16:56:36.000Z      Giveaway  
2  2022-08-06T16:56:35.000Z  Appreciation  
3  2022-08-06T16:56:35.000Z     Community  
4  2022-08-06T16:56:34.000Z     Community

# Droping unwanted columns :

In [7]:
df1=df1.dropna()  

In [8]:
df1=df1.drop(['id','tweet_created_at'],axis=1)

In [9]:
df1['tweet_text']

0        @crypto_brody @eCoLoGy1990 @MoonrunnersNFT @It...
1        Need Sick Character art❓#art #artist #Artist...
2        @The_Hulk_NFT @INagotchiNFT @Tesla @killabears...
3        @CryptoBatzNFT @DarekBTW The first project in ...
4        @sashadysonn The first project in crypto with ...
                               ...                        
96359    @nft_cryptogang @liuyan93721534 0x9fE808D8a9E2...
96360    Just registered to win @cryptopunksnfts #1859 ...
96361    @SolSniffer Dyor on the nft collection "Dictat...
96362    #NFT #NFTCommmunity #DeltaFlare\nJoin me on Di...
96363    @DuckBathing @diozoth @elonmusk @richerd @John...
Name: tweet_text, Length: 96364, dtype: object

# Starts cleaning the data :

In [10]:
df1['tweet_processed'] = df1['tweet_text'].str.replace("[^a-zA-Z]", " ")

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  """Entry point for launching an IPython kernel.


In [11]:
df1['tweet_processed'] = df1['tweet_processed'].apply(lambda row: ' '.join([word for word in row.split() if len(word)>2]))

In [12]:
df1['tweet_processed']

0        crypto brody eCoLoGy MoonrunnersNFT ItsukiNFT ...
1        Need Sick Character art art artist Artists ani...
2        The Hulk NFT INagotchiNFT Tesla killabearsnft ...
3        CryptoBatzNFT DarekBTW The first project crypt...
4        sashadysonn The first project crypto with move...
                               ...                        
96359                     nft cryptogang liuyan Thanks lot
96360    Just registered win cryptopunksnfts with blokp...
96361    SolSniffer Dyor the nft collection Dictators t...
96362    NFT NFTCommmunity DeltaFlare Join Discord http...
96363    DuckBathing diozoth elonmusk richerd John NFT ...
Name: tweet_processed, Length: 96364, dtype: object

In [13]:
df1['tweet_processed'] = [tweet.lower() for tweet in df1['tweet_processed']]

In [14]:
df1['tweet_processed']

0        crypto brody ecology moonrunnersnft itsukinft ...
1        need sick character art art artist artists ani...
2        the hulk nft inagotchinft tesla killabearsnft ...
3        cryptobatznft darekbtw the first project crypt...
4        sashadysonn the first project crypto with move...
                               ...                        
96359                     nft cryptogang liuyan thanks lot
96360    just registered win cryptopunksnfts with blokp...
96361    solsniffer dyor the nft collection dictators t...
96362    nft nftcommmunity deltaflare join discord http...
96363    duckbathing diozoth elonmusk richerd john nft ...
Name: tweet_processed, Length: 96364, dtype: object

# Using Word Tokenize and StopWords Removal : 

In [15]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk import word_tokenize
stop_words = stopwords.words('english')
# Function to remove stop words 
def remove_stopwords(tweet):
    # iNPUT : IT WILL TAKE ROW/REVIEW AS AN INPUT
    # take the paragraph, break into words, check if the word is a stop word, remove if stop word, combine the words into a para again
    tweet_tokenized = word_tokenize(tweet)
    tweet_new = " ".join([i for i in tweet_tokenized  if i not in stop_words])
    return tweet_new
df1['tweet_processed'] = [remove_stopwords(tweet) for tweet in df1['tweet_processed']]


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [16]:
df1['tweet_processed']

0        crypto brody ecology moonrunnersnft itsukinft ...
1        need sick character art art artist artists ani...
2        hulk nft inagotchinft tesla killabearsnft elon...
3        cryptobatznft darekbtw first project crypto mo...
4        sashadysonn first project crypto move earn ast...
                               ...                        
96359                     nft cryptogang liuyan thanks lot
96360    registered win cryptopunksnfts blokpax let fre...
96361    solsniffer dyor nft collection dictators build...
96362    nft nftcommmunity deltaflare join discord http...
96363    duckbathing diozoth elonmusk richerd john nft ...
Name: tweet_processed, Length: 96364, dtype: object

# Using Lemmatizer Function :

In [18]:
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('averaged_perceptron_tagger')
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet

# function to convert nltk tag to wordnet tag
lemmatizer = WordNetLemmatizer()

# Finds the part of speech tag
# Convert the detailed POS tag into a shallow information
def nltk_tag_to_wordnet_tag(nltk_tag):
    if nltk_tag.startswith('J'):
        return wordnet.ADJ
    elif nltk_tag.startswith('V'):
        return wordnet.VERB
    elif nltk_tag.startswith('N'):
        return wordnet.NOUN
    elif nltk_tag.startswith('R'):
        return wordnet.ADV
    else:          
        return None

# lemmatize sentence using pos tag
def lemmatize_sentence(sentence):
  # word tokenize -> pos tag (detailed) -> wordnet tag (shallow pos) -> lemmatizer -> root word
    #tokenize the sentence and find the POS tag for each token
    nltk_tagged = nltk.pos_tag(nltk.word_tokenize(sentence))  
    #tuple of (token, wordnet_tag)
    wordnet_tagged = map(lambda x: (x[0], nltk_tag_to_wordnet_tag(x[1])), nltk_tagged)
    lemmatized_sentence = []
    for word, tag in wordnet_tagged:
        if tag is None:
            #if there is no available tag, append the token as is
            lemmatized_sentence.append(word)
        else:        
            #else use the tag to lemmatize the token
            lemmatized_sentence.append(lemmatizer.lemmatize(word, tag))
    return " ".join(lemmatized_sentence)


df1['tweet_processed'] = df1['tweet_processed'].apply(lambda x: lemmatize_sentence(x))

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


In [19]:
df1['tweet_intent'].unique()

array(['Community', 'Giveaway', 'Appreciation', 'Presale', 'Whitelist',
       'pinksale', 'Done', 'Interested', 'Launching Soon'], dtype=object)

# Using TF-IDF Function :
# Encoding and Splitting the Data.

In [20]:
# Importing module
from sklearn.feature_extraction.text import TfidfVectorizer
import sklearn
# Creating matrix of top 2500 tokens
tfidf = TfidfVectorizer(max_features=2500)
 

X = tfidf.fit_transform(df1.tweet_processed).toarray()
from sklearn import preprocessing


y = df1['tweet_intent'].map({'Community':0,'Giveaway':1, 'Appreciation':2, 'Presale':3, 'Whitelist':4,'pinksale':5, 'Done':6, 'Interested':7, 'Launching Soon':8})
featureNames = tfidf.get_feature_names()


X, y


# Splitting the dataset into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [21]:
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [22]:
y.unique()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
X_train.shape, X_test.shape

((77091, 2500), (19273, 2500))

# Implementing Gaussian Naive Bayes model :

In [24]:
# training the model on training set
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)

GaussianNB()

In [25]:
# making predictions on the testing set
y_pred = gnb.predict(X_test)

In [26]:
# comparing actual response values (y_test) with predicted response values (y_pred)
from sklearn import metrics
print("Gaussian Naive Bayes model accuracy(in %):", metrics.accuracy_score(y_test, y_pred)*100)

Gaussian Naive Bayes model accuracy(in %): 64.39578685207285


# **OUTPUT :**
# Gaussian Naive Bayes model accuracy(in %): **65.6306750376174**

# Implementing Logistic Regression Model :

In [27]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression(random_state = 0)
log_reg.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression(random_state=0)

In [28]:
y_pred = log_reg.predict(X_test)

In [29]:
accuracy_test_set = log_reg.score(X_test, y_test)
accuracy_test_set

0.9668966948580916

In [30]:
print("{0:.2f}".format(round(accuracy_test_set, 2)))

0.97


In [31]:
from sklearn.metrics import roc_auc_score

In [32]:
roc_auc_score(y_test, log_reg.predict_proba(X_test),multi_class="ovr")

0.9961294811773109

In [33]:

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
  
print ("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[8217    4   45    1   20    0    0    1    0]
 [  53 4083   55    1   15    1    4    1    0]
 [  20    7 3196    3   41    0   12    2    0]
 [   5    2    2  985    6    0    0    1    0]
 [ 128   21  115   13 1402    0    2    1    1]
 [   1    0    0    0    2  100    0    0    0]
 [  16    1   15    0    9    0  582    0    0]
 [   2    1    5    0    3    0    0   44    0]
 [   0    0    0    0    0    0    0    0   26]]


# **OUTPUT :**
# Logistic Regression model accuracy: **0.9959990208680227**
# **Conclusion :**
# Logistic Regression model will gives higher accuracy so we select this model for final predictions.

# Applying Test Dataset to filling the missed Intents :

# Loading the Dataset :

In [34]:
data=pd.read_csv("/content/drive/MyDrive/Tweet_NFT.xlsx - Sheet1.csv")

In [35]:
df2=pd.DataFrame(data)

In [36]:
df2.head()

id                                         tweet_text  \
0  1212762  @crypto_brody @eCoLoGy1990 @MoonrunnersNFT @It...   
1  1212763  Need Sick Character art❓#art #artist #Artist...   
2  1212765  @The_Hulk_NFT @INagotchiNFT @Tesla @killabears...   
3  1212766  @CryptoBatzNFT @DarekBTW The first project in ...   
4  1212767  @sashadysonn The first project in crypto with ...   

           tweet_created_at  tweet_intent  
0  2022-08-06T16:56:36.000Z     Community  
1  2022-08-06T16:56:36.000Z      Giveaway  
2  2022-08-06T16:56:35.000Z  Appreciation  
3  2022-08-06T16:56:35.000Z     Community  
4  2022-08-06T16:56:34.000Z     Community

In [37]:
df2=df2.iloc[96365:,[1,3]]

In [38]:
df2.head()

tweet_text tweet_intent
96365  @asksabir007 @dao_lm Don't miss the chance to ...          NaN
96366  This zesty faucet from @_bitcoiner is making m...          NaN
96367  15% off 🧙‍♂️ #Wizardia NFTs - it's a ...          NaN
96368  @Kavaboy_NFT @tanya_4d Message me, let’s tal...          NaN
96369  @berylbilici glad you stayed. The NFT world ke...          NaN

In [39]:
df2['tweet_intent'].count()

0

# Starts Cleaning :

In [40]:
df2['tweet_processed'] = df2['tweet_text'].str.replace("[^a-zA-Z]", " ")

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  """Entry point for launching an IPython kernel.


In [41]:
df2['tweet_processed'] = df2['tweet_processed'].apply(lambda row: ' '.join([word for word in row.split() if len(word)>2]))

In [42]:
df2['tweet_processed']

96365     asksabir dao Don miss the chance win NFT worth...
96366     This zesty faucet from bitcoiner making tweet ...
96367     off Wizardia NFTs game magic filled metaverse ...
96368     Kavaboy NFT tanya Message let talk about some ...
96369     berylbilici glad you stayed The NFT world keep...
                                ...                        
127448    Jason company Universe solving this and got th...
127449                BosoTokyo Many will get rekt this NFT
127450    leeneedham KibaInuWorld HODL OFFICIAL KoaComba...
127451                          UNLEASHED NFT love this job
127452                Shill Ronin UNLEASHED NFT proof https
Name: tweet_processed, Length: 31088, dtype: object

In [43]:
df2['tweet_processed'] = [tweet.lower() for tweet in df2['tweet_processed']]

In [44]:
df2['tweet_processed']

96365     asksabir dao don miss the chance win nft worth...
96366     this zesty faucet from bitcoiner making tweet ...
96367     off wizardia nfts game magic filled metaverse ...
96368     kavaboy nft tanya message let talk about some ...
96369     berylbilici glad you stayed the nft world keep...
                                ...                        
127448    jason company universe solving this and got th...
127449                bosotokyo many will get rekt this nft
127450    leeneedham kibainuworld hodl official koacomba...
127451                          unleashed nft love this job
127452                shill ronin unleashed nft proof https
Name: tweet_processed, Length: 31088, dtype: object

# Applying Word Tokenizer and StopWords Removal Function :

In [45]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk import word_tokenize
stop_words = stopwords.words('english')
# Function to remove stop words 
def remove_stopwords(tweet):
    # iNPUT : IT WILL TAKE ROW/REVIEW AS AN INPUT
    # take the paragraph, break into words, check if the word is a stop word, remove if stop word, combine the words into a para again
    tweet_tokenized = word_tokenize(tweet)
    tweet_new = " ".join([i for i in tweet_tokenized  if i not in stop_words])
    return tweet_new
df2['tweet_processed'] = [remove_stopwords(tweet) for tweet in df2['tweet_processed']]


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [46]:
df2['tweet_processed']

96365     asksabir dao miss chance win nft worth simple ...
96366     zesty faucet bitcoiner making tweet claim free...
96367     wizardia nfts game magic filled metaverse aren...
96368     kavaboy nft tanya message let talk marketing p...
96369     berylbilici glad stayed nft world keeps growin...
                                ...                        
127448    jason company universe solving got columbia st...
127449                          bosotokyo many get rekt nft
127450    leeneedham kibainuworld hodl official koacomba...
127451                               unleashed nft love job
127452                shill ronin unleashed nft proof https
Name: tweet_processed, Length: 31088, dtype: object

# Applying Lemmatizer Function :

In [47]:
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('averaged_perceptron_tagger')
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet

# function to convert nltk tag to wordnet tag
lemmatizer = WordNetLemmatizer()

# Finds the part of speech tag
# Convert the detailed POS tag into a shallow information
def nltk_tag_to_wordnet_tag(nltk_tag):
    if nltk_tag.startswith('J'):
        return wordnet.ADJ
    elif nltk_tag.startswith('V'):
        return wordnet.VERB
    elif nltk_tag.startswith('N'):
        return wordnet.NOUN
    elif nltk_tag.startswith('R'):
        return wordnet.ADV
    else:          
        return None

# lemmatize sentence using pos tag
def lemmatize_sentence(sentence):
  # word tokenize -> pos tag (detailed) -> wordnet tag (shallow pos) -> lemmatizer -> root word
    #tokenize the sentence and find the POS tag for each token
    nltk_tagged = nltk.pos_tag(nltk.word_tokenize(sentence))  
    #tuple of (token, wordnet_tag)
    wordnet_tagged = map(lambda x: (x[0], nltk_tag_to_wordnet_tag(x[1])), nltk_tagged)
    lemmatized_sentence = []
    for word, tag in wordnet_tagged:
        if tag is None:
            #if there is no available tag, append the token as is
            lemmatized_sentence.append(word)
        else:        
            #else use the tag to lemmatize the token
            lemmatized_sentence.append(lemmatizer.lemmatize(word, tag))
    return " ".join(lemmatized_sentence)


df2['tweet_processed'] = df2['tweet_processed'].apply(lambda x: lemmatize_sentence(x))

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


In [48]:
df2['tweet_intent'].unique()

array([nan], dtype=object)

In [49]:
x_test1=df2.drop("tweet_intent",axis=1)

In [50]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression(random_state = 0)
log_reg.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression(random_state=0)

# Applying TF_IDF Function :

In [51]:
# Importing module
from sklearn.feature_extraction.text import TfidfVectorizer
import sklearn
# Creating matrix of top 2500 tokens
tfidf = TfidfVectorizer(max_features=2500)
 
x_test1 = tfidf.fit_transform(df2.tweet_processed).toarray()

featureNames = tfidf.get_feature_names()


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


# Predicting the Test Data :

In [52]:
X_train.shape, x_test1.shape

((77091, 2500), (31088, 2500))

In [53]:
y_pred = log_reg.predict(x_test1)
y_pred

array([2, 0, 1, ..., 0, 4, 2])

In [54]:
y_pred.shape

(31088,)

In [55]:
df2.drop("tweet_intent",axis=1)

tweet_text  \
96365   @asksabir007 @dao_lm Don't miss the chance to ...   
96366   This zesty faucet from @_bitcoiner is making m...   
96367   15% off 🧙‍♂️ #Wizardia NFTs - it's a ...   
96368   @Kavaboy_NFT @tanya_4d Message me, let’s tal...   
96369   @berylbilici glad you stayed. The NFT world ke...   
...                                                   ...   
127448  @Jason My company Universe is solving this, an...   
127449          @BosoTokyo Many will get rekt in this NFT   
127450  @leeneedham81 @KibaInuWorld @HODL_OFFICIAL @Ko...   
127451             @1kz3ro @UNLEASHED_NFT I love this job   
127452  @Shill_Ronin @UNLEASHED_NFT my proof https://t...   

                                          tweet_processed  
96365   asksabir dao miss chance win nft worth simple ...  
96366   zesty faucet bitcoiner make tweet claim free n...  
96367   wizardia nfts game magic fill metaverse arena ...  
96368   kavaboy nft tanya message let talk marketing p...  
96369       berylbilici glad stay nft world keep grow day  
...                                                   ...  
127448  jason company universe solve get columbia star...  
127449                        bosotokyo many get rekt nft  
127450  leeneedham kibainuworld hodl official koacomba...  
127451                             unleashed nft love job  
127452               shill ronin unleashed nft proof http  

[31088 rows x 2 columns]

In [56]:
df2['tweet_intent']=y_pred

In [57]:
df2['tweet_intent'].unique()

array([2, 0, 1, 4, 3, 6, 5, 7])

# Reversing the Encoded Data :

In [58]:
df2['tweet_intent']=df2['tweet_intent'].map({0:'Community',1:'Giveaway',2:'Appreciation',3:'Presale',4:'Whitelist',5:'pinksale', 6:'Done', 7:'Interested', 8:'Launching Soon'})

In [59]:
df2['tweet_intent'].unique()

array(['Appreciation', 'Community', 'Giveaway', 'Whitelist', 'Presale',
       'Done', 'pinksale', 'Interested'], dtype=object)

In [60]:
df2

tweet_text  tweet_intent  \
96365   @asksabir007 @dao_lm Don't miss the chance to ...  Appreciation   
96366   This zesty faucet from @_bitcoiner is making m...     Community   
96367   15% off 🧙‍♂️ #Wizardia NFTs - it's a ...      Giveaway   
96368   @Kavaboy_NFT @tanya_4d Message me, let’s tal...     Community   
96369   @berylbilici glad you stayed. The NFT world ke...     Community   
...                                                   ...           ...   
127448  @Jason My company Universe is solving this, an...     Whitelist   
127449          @BosoTokyo Many will get rekt in this NFT     Community   
127450  @leeneedham81 @KibaInuWorld @HODL_OFFICIAL @Ko...     Community   
127451             @1kz3ro @UNLEASHED_NFT I love this job     Whitelist   
127452  @Shill_Ronin @UNLEASHED_NFT my proof https://t...  Appreciation   

                                          tweet_processed  
96365   asksabir dao miss chance win nft worth simple ...  
96366   zesty faucet bitcoiner make tweet claim free n...  
96367   wizardia nfts game magic fill metaverse arena ...  
96368   kavaboy nft tanya message let talk marketing p...  
96369       berylbilici glad stay nft world keep grow day  
...                                                   ...  
127448  jason company universe solve get columbia star...  
127449                        bosotokyo many get rekt nft  
127450  leeneedham kibainuworld hodl official koacomba...  
127451                             unleashed nft love job  
127452               shill ronin unleashed nft proof http  

[31088 rows x 3 columns]

# **Final Output :**

In [64]:
df3=pd.concat([df1,df2])
df3

tweet_text  tweet_intent  \
0       @crypto_brody @eCoLoGy1990 @MoonrunnersNFT @It...     Community   
1       Need Sick Character art❓#art #artist #Artist...      Giveaway   
2       @The_Hulk_NFT @INagotchiNFT @Tesla @killabears...  Appreciation   
3       @CryptoBatzNFT @DarekBTW The first project in ...     Community   
4       @sashadysonn The first project in crypto with ...     Community   
...                                                   ...           ...   
127448  @Jason My company Universe is solving this, an...     Whitelist   
127449          @BosoTokyo Many will get rekt in this NFT     Community   
127450  @leeneedham81 @KibaInuWorld @HODL_OFFICIAL @Ko...     Community   
127451             @1kz3ro @UNLEASHED_NFT I love this job     Whitelist   
127452  @Shill_Ronin @UNLEASHED_NFT my proof https://t...  Appreciation   

                                          tweet_processed  
0       crypto brody ecology moonrunnersnft itsukinft ...  
1       need sick character art art artist artist anim...  
2       hulk nft inagotchinft tesla killabearsnft elon...  
3       cryptobatznft darekbtw first project crypto mo...  
4       sashadysonn first project crypto move earn ast...  
...                                                   ...  
127448  jason company universe solve get columbia star...  
127449                        bosotokyo many get rekt nft  
127450  leeneedham kibainuworld hodl official koacomba...  
127451                             unleashed nft love job  
127452               shill ronin unleashed nft proof http  

[127452 rows x 3 columns]

In [65]:
# Re ordering columns
df3 = df3[['tweet_text','tweet_processed','tweet_intent']]
df3

tweet_text  \
0       @crypto_brody @eCoLoGy1990 @MoonrunnersNFT @It...   
1       Need Sick Character art❓#art #artist #Artist...   
2       @The_Hulk_NFT @INagotchiNFT @Tesla @killabears...   
3       @CryptoBatzNFT @DarekBTW The first project in ...   
4       @sashadysonn The first project in crypto with ...   
...                                                   ...   
127448  @Jason My company Universe is solving this, an...   
127449          @BosoTokyo Many will get rekt in this NFT   
127450  @leeneedham81 @KibaInuWorld @HODL_OFFICIAL @Ko...   
127451             @1kz3ro @UNLEASHED_NFT I love this job   
127452  @Shill_Ronin @UNLEASHED_NFT my proof https://t...   

                                          tweet_processed  tweet_intent  
0       crypto brody ecology moonrunnersnft itsukinft ...     Community  
1       need sick character art art artist artist anim...      Giveaway  
2       hulk nft inagotchinft tesla killabearsnft elon...  Appreciation  
3       cryptobatznft darekbtw first project crypto mo...     Community  
4       sashadysonn first project crypto move earn ast...     Community  
...                                                   ...           ...  
127448  jason company universe solve get columbia star...     Whitelist  
127449                        bosotokyo many get rekt nft     Community  
127450  leeneedham kibainuworld hodl official koacomba...     Community  
127451                             unleashed nft love job     Whitelist  
127452               shill ronin unleashed nft proof http  Appreciation  

[127452 rows x 3 columns]

# **Saving the updated Intents :**

In [66]:
df3.to_csv("Tweet_NFT_Updated.csv",index=False) 