<a href="https://colab.research.google.com/github/mcasivaram/Datascience/blob/main/Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [34]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
print(np.__version__)
np.show_config()

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
x=np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
x=np.zeros((10,10))
print(x.size*x.itemsize)

800


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
z=np.zeros(10)
z[4]=1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
z=np.arange(10,50)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
z=np.arange(50)
z[::-1]


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
z=np.arange(9).reshape(3,3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
z=np.nonzero([1,2,0,0,4,0])
z

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
z=np.eye(3,3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
z=np.random.random([3,3,3])
z

array([[[0.17114501, 0.83186492, 0.4712461 ],
        [0.60066974, 0.53787702, 0.8530471 ],
        [0.26458051, 0.87405901, 0.45411302]],

       [[0.92710694, 0.5207889 , 0.90781095],
        [0.18486411, 0.25616548, 0.71749258],
        [0.08371285, 0.59578505, 0.71322762]],

       [[0.85162705, 0.21103353, 0.98599558],
        [0.7562385 , 0.12393593, 0.52664359],
        [0.66710235, 0.78792963, 0.47845826]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
z=np.random.random((10,10))
print(z.min(),z.max())

0.006401744668632858 0.9615213268712374


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
z=np.random.random(30)
print(z.mean())

0.432129366133269


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
z=np.ones((10,10))
z[1:-1,1:-1]=0
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
z=np.ones((10,10))
z=np.pad(z,pad_width=1,mode='constant',constant_values=0)
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
z=np.diag(1+np.arange(4),k=-1)
z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
z=np.zeros((8,8))
z[1::2,::2]=1
z[::2,1::2]=1
z

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:

z=np.tile(np.array([[0,1],[1,0]]),(4,4))
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
z=np.random.random((5,5))
zmin=z.min()
zmax=z.max()
z=((z-zmin)/(zmax-zmin))
z

array([[0.135163  , 0.3859746 , 0.89641289, 0.37225747, 0.40777702],
       [0.        , 0.0494776 , 0.32985975, 0.33969762, 0.45584153],
       [0.4888019 , 1.        , 0.50180721, 0.77332936, 0.477794  ],
       [0.81993471, 0.76901617, 0.35875799, 0.957791  , 0.53409319],
       [0.67957497, 0.61634263, 0.23000558, 0.19063613, 0.95062259]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
z=np.dtype([("r",np.ubyte,1),("g",np.ubyte,1),("b",np.ubyte,1),("a",np.ubyte,1)])
z


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """Entry point for launching an IPython kernel.


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
#z=np.dot(np.ones((5,3)),np.ones((3,2)))
z=np.ones((5,3))@np.ones((3,2))
z

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
z=np.arange(20)
z[(z>3)&(z<=8)]*=-1
z

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:

Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
z = np.random.uniform(-10,+10,10)

print (np.copysign(np.ceil(np.abs(z)),z))

[ -5.  -9.   6.   9.  -9.   8.   2.  -7. -10.  -6.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
#z=np.random.random((0,10,10))
#x=np.random.random((0,10,10))
z=np.arange(10)
x=np.arange(3)
y=np.intersect1d(z,x)
y

array([0, 1, 2])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
z=np.seterr(all="ignore")
x=np.ones(1)/0
x
y=np.errstate(divide="ignore")
x

array([inf])

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
y=np.datetime64('today','D')-np.timedelta64(1,'D')
t=np.datetime64('today','D')
to=np.datetime64('today','D')+np.timedelta64(1,'D')
print(y)
print(t)
print(to)

2022-05-18
2022-05-19
2022-05-20


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
y=np.arange('2022-07','2022-08',dtype='datetime64[D]')
y

array(['2022-07-01', '2022-07-02', '2022-07-03', '2022-07-04',
       '2022-07-05', '2022-07-06', '2022-07-07', '2022-07-08',
       '2022-07-09', '2022-07-10', '2022-07-11', '2022-07-12',
       '2022-07-13', '2022-07-14', '2022-07-15', '2022-07-16',
       '2022-07-17', '2022-07-18', '2022-07-19', '2022-07-20',
       '2022-07-21', '2022-07-22', '2022-07-23', '2022-07-24',
       '2022-07-25', '2022-07-26', '2022-07-27', '2022-07-28',
       '2022-07-29', '2022-07-30', '2022-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
a=np.ones(4)*1
b=np.ones(4)*2
c=np.ones(4)*3
z=np.add(a,b,out=b)
x=np.negative(a,out=a)
c=np.multiply(a,b,out=a)
v=np.divide(a,2,out=a)
print(z)
print(x)
print(c)
print(v)

[2. 2. 2. 2.]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
z=np.random.uniform(0,10,20)
print(z-z%1)
print(np.floor(z))
print(np.ceil(z)-1)
print(z.astype(int))
print(np.trunc(z))


[9. 0. 3. 0. 0. 0. 9. 4. 5. 1. 9. 6. 6. 7. 4. 7. 4. 9. 9. 8.]
[9. 0. 3. 0. 0. 0. 9. 4. 5. 1. 9. 6. 6. 7. 4. 7. 4. 9. 9. 8.]
[9. 0. 3. 0. 0. 0. 9. 4. 5. 1. 9. 6. 6. 7. 4. 7. 4. 9. 9. 8.]
[9 0 3 0 0 0 9 4 5 1 9 6 6 7 4 7 4 9 9 8]
[9. 0. 3. 0. 0. 0. 9. 4. 5. 1. 9. 6. 6. 7. 4. 7. 4. 9. 9. 8.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
z=np.zeros((5,5))
z+=np.arange(5)
z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def generator():
 for i in range(10):
   yield i
z=np.fromiter(generator(),dtype=float,count=-1)
z   

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
z=np.linspace(0,1,num=12)[1:-1]
z

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
z=np.random.random(10)
z.sort()
z

array([0.01551928, 0.03545876, 0.13374473, 0.20061529, 0.27083774,
       0.33980955, 0.46617175, 0.63130128, 0.67487569, 0.67848022])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
z=np.arange(10)
np.add.reduce(z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
a=np.random.randint(1,5)
b=np.random.randint(1,5)
z=np.allclose(a,b)
print(z)
z=np.array_equal(a,b)
print(z)

True
True


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
z=np.ones(10)
z.flags.writeable=False
#z[1]=5 if we include this statement it will returns error 
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
z=np.random.random((10,20))
x,c=z[:,0],z[:,1]
a=np.sqrt(x**2+c**2)
print(a)
b=np.arctan2(x,c)
print(b)

[0.77720224 0.48612414 0.40131749 0.97391013 0.46895062 0.38196014
 0.48409971 0.77613016 0.82038577 1.15736571]
[0.04506379 0.84811011 0.39488081 1.22312172 0.73421387 0.58892135
 0.3935511  0.89253081 1.51459423 0.90310137]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
z=np.random.random(10)
z[z.argmax()]=0
print(z)


[0.43719881 0.09340139 0.         0.02643063 0.69820693 0.16041746
 0.83420074 0.09446187 0.52898147 0.22521661]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
z=np.zeros((5,5),[('x','float'),('y','float')])
z['x'],z['y']=np.meshgrid(np.linspace(0,1,num=5),np.linspace(0,1,num=5))
print(z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
z=np.arange(10)
x=z+1.5
c=1/np.subtract.outer(z,x)
print(np.linalg.det(c))

-85.11762642807601


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for dtype in [np.int16,np.int32,np.int64]:
  print(np.iinfo(dtype).min)
  print(np.iinfo(dtype).max)
for dtype in [np.float16,np.float32,np.float64]:
  print(np.finfo(dtype).min) 
  print(np.finfo(dtype).max) 
  print(np.finfo(dtype).eps)


-32768
32767
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-65500.0
65500.0
0.000977
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
np.set_printoptions(threshold=np.sys.maxsize)
z=np.ones((16,16))
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
z=np.arange(100)
v=np.random.uniform(0,100)
i=(np.abs(z-v)).argmin()
print(z[i])

14


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
z=np.zeros(10,[('position',[('x',float),('y',float)]),('color',[('r',float),('g',float),('b',float)])])
z

array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [3]:
z=np.random.random((100,2))
x,y=np.atleast_2d(z[:,0],z[:,1])
d=np.sqrt((x-x.T)**2+(y-y.T)**2)
print(d)

[[0.         0.24633042 0.20918607 ... 0.09213855 0.56792289 0.79578613]
 [0.24633042 0.         0.33608597 ... 0.33473482 0.44659532 0.60687039]
 [0.20918607 0.33608597 0.         ... 0.24868887 0.44792343 0.71773993]
 ...
 [0.09213855 0.33473482 0.24868887 ... 0.         0.64950316 0.88522642]
 [0.56792289 0.44659532 0.44792343 ... 0.64950316 0.         0.28839867]
 [0.79578613 0.60687039 0.71773993 ... 0.88522642 0.28839867 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [14]:
z=np.arange(10,dtype=np.float32)
z=z.astype(np.int32,copy=True)
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [15]:
from io import StringIO
s=StringIO("""1, 2, 3, 4, 5\n
6, , , 7, 8\n
, , 9,10,11\n""")
z=np.genfromtxt(s,delimiter=",",dtype=np.int)
print(z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [16]:
z=np.arange(9).reshape(3,3)
for index,value in np.ndenumerate(z):
  print(index,value)
for index in np.ndindex(z.shape):
  print(index,z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [18]:
x,y=np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d=np.sqrt(x*x+y*y)
sigma,mu=1.0, 0.0
g=np.exp(-((d-mu)**2/(2.0*sigma**2)))
print(g)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [19]:
n=10
p=3
z=np.zeros((n,n))
np.put(z,np.random.choice(range(n*n),p,replace=False),1)
print(z)

[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [21]:
x=np.random.rand(5,10)
y=x-x.mean(axis=1,keepdims=True)
y

array([[ 0.30204199,  0.34145054, -0.05645011, -0.13525701, -0.05671112,
        -0.23351499, -0.32094946, -0.11236575, -0.31394677,  0.58570269],
       [ 0.39495031,  0.21836641, -0.37448128, -0.09890873,  0.15379149,
         0.13357356, -0.33076185, -0.43816784,  0.47191067, -0.13027274],
       [ 0.04376681, -0.00973038,  0.29515329, -0.27694866, -0.46108806,
        -0.06811404,  0.00592715,  0.34137509,  0.0476298 ,  0.082029  ],
       [ 0.09943827, -0.35370372, -0.33671271,  0.3545839 , -0.37447386,
         0.24776513, -0.14496098, -0.3038437 ,  0.50105406,  0.3108536 ],
       [ 0.3317987 ,  0.34041357,  0.55978376, -0.34878305,  0.14849199,
        -0.12183112, -0.39016959, -0.35457129, -0.37262535,  0.20749237]])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [22]:
z=np.random.randint(0,10,(3,3))
print(z)
print(z[z[:,1].argsort()])

[[1 9 9]
 [3 8 7]
 [4 2 6]]
[[4 2 6]
 [3 8 7]
 [1 9 9]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [25]:
z=np.random.randint(0,3,(3,10))
print((~z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [26]:
z1=np.random.uniform(0,1,10)
z2=0.5
m=z1.flat[np.abs(z1-z2).argmin()]
print(m)

0.4944958213497376


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [28]:
a=np.arange(3).reshape(3,1)
b=np.arange(3).reshape(1,3)
it=np.nditer([a,b,None])
for x,y,z in it: 
  z[...] = x + y
  print(it.operands[2])

[[0 9 9]
 [3 8 7]
 [4 2 6]]
[[0 1 9]
 [3 8 7]
 [4 2 6]]
[[0 1 2]
 [3 8 7]
 [4 2 6]]
[[0 1 2]
 [1 8 7]
 [4 2 6]]
[[0 1 2]
 [1 2 7]
 [4 2 6]]
[[0 1 2]
 [1 2 3]
 [4 2 6]]
[[0 1 2]
 [1 2 3]
 [2 2 6]]
[[0 1 2]
 [1 2 3]
 [2 3 6]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [32]:
class NamedArray(np.ndarray):
  #obj=0

  def __new__(cls, array, name="no name"):

    obj = np.asarray(array).view(cls)

    obj.name = name

    return obj

  def __array_finalize__(self, obj):

    if obj is None: 
      return

      self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")

print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [33]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[2. 1. 1. 3. 3. 2. 4. 6. 2. 6.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [37]:
x = [1,2,3,4,5,6]
i = [1,3,9,3,4,1]
f = np.bincount(i,x)
print(f)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [38]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [39]:
a = np.random.randint(0,10,(3,4,3,4))
sum = a.sum(axis=(-2,-1))
print(sum)

[[52 42 44 34]
 [50 51 51 50]
 [54 54 52 41]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [40]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.54961432 0.6057714  0.36340506 0.48527542 0.4964538  0.37573926
 0.37340672 0.51693857 0.53184739 0.5717597 ]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [47]:
a=np.random.uniform(0,1,(5,5))
b=np.random.uniform(0,1,(5,5))
z= np.diag(np.dot(a,b))
z

array([2.30753791, 0.82030235, 1.63865849, 1.19842745, 0.40656365])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [48]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [53]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [54]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [55]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0,  8) ( 0, 51) ( 2,  2) ( 2, 65) ( 7, 20) ( 7, 60) ( 8, 51) (20, 60)
 (26, 29) (26, 39) (26, 90) (26, 92) (28, 65) (28, 97) (29, 90) (35, 56)
 (35, 79) (39, 92) (45, 62) (45, 74) (48, 92) (48, 94) (56, 79) (57, 60)
 (57, 73) (60, 73) (62, 74) (65, 97) (92, 94)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [56]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [57]:
def moving_average(a, n=3) :
 ret = np.cumsum(a, dtype=float)
 ret[n:] = ret[n:] - ret[:-n]
 return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [58]:
from numpy.lib import stride_tricks
def rolling(a, window):
 shape = (a.size - window + 1, window)
 strides = (a.itemsize, a.itemsize)
 return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [59]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.23360568,  0.40735296,  0.0881021 ,  0.66289623,  0.62095885,
       -0.10427595, -0.41825497, -0.22952239,  0.39369067, -0.42759048,
        0.14479588,  0.04624856,  0.52018647,  0.62434365,  0.40214152,
       -0.75149084,  0.19679554, -0.45283986,  0.35605173,  0.42985558,
       -0.82092307, -0.05408901,  0.65976655, -0.76484907,  0.42298933,
       -0.14983533,  0.12067055,  0.80911172, -0.42996417, -0.76456162,
        0.75079047, -0.82556155,  0.54785489, -0.49842325, -0.71040329,
        0.15650256, -0.24899091, -0.44505726, -0.69488973, -0.55048495,
        0.45362955, -0.61700918,  0.14973588, -0.33031867, -0.50197691,
       -0.46436413,  0.30757643, -0.31533687, -0.84816914,  0.29512214,
        0.70228309,  0.37770941,  0.9761794 ,  0.22363318, -0.37219204,
        0.76996465, -0.09429543, -0.85897442, -0.95548492,  0.0108716 ,
        0.63974037,  0.25083066, -0.84671979, -0.33947798,  0.44248821,
        0.42362014, -0.2237382 ,  0.83357942, -0.61528855,  0.74

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [60]:
def distance(P0, P1, p):
 T = P1 - P0
 L = (T**2).sum(axis=1)
 U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
 U = U.reshape(len(U),1)
 D = P0 + U*T - p
 return np.sqrt((D**2).sum(axis=1))
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 1.49004805  8.02046963  4.17291859 16.63486475  1.72891848 11.19369664
 12.16896779 13.37498394  3.51918375  0.41945043]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [61]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 4.82246044 17.99485974  3.00888914  6.32468304  9.99783575  0.08716401
  12.49329312 10.11199527  8.53275522  1.11245952]
 [ 8.23018004  4.27124855  5.63739076  0.45224147  0.1867921   3.82868393
   1.14955319  3.2758906   4.60961896  7.18646876]
 [ 4.85502091 10.20010811 10.16202992  7.17864383  8.06562612  3.16583305
   8.87299397  0.71124891  0.73002604  8.41719656]
 [ 1.71270787 13.04420806  8.52400889  7.67467855  9.39574849  2.95310593
  10.67866634  3.83280748  2.61978804  5.7670847 ]
 [ 5.87104262  5.51366473  2.45543842  2.28491307  0.81838698  6.23227399
   0.70835459  1.12937656  7.86418125  3.9302412 ]
 [ 9.36869368  5.02561511 10.13341775  3.77612999  3.71056939  0.73405808
   4.08731524  4.01298535  0.25504966 10.67870064]
 [ 4.69972638 11.17318753 11.9013927   9.25928256  9.99979383  5.24762832
  10.63768892  1.04924929  0.88836934  9.46728448]
 [ 0.25631201 16.0541722  10.18221039 11.01788476 12.98479718  5.90555565
  14.28110164  6.05979056  1.27938625  5.84831558]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [62]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill = 0
position = (1,1)
R = np.ones(shape, dtype=Z.dtype)*fill
P = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)
R_start = np.zeros((len(shape),)).astype(int)
R_stop = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop = (P+Rs//2)+Rs%2
R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()
r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[9 3 5 3 0 5 3 5 6 6]
 [2 8 1 6 5 6 8 5 4 4]
 [3 4 2 7 4 3 7 4 8 2]
 [2 8 3 6 8 4 3 7 4 1]
 [6 2 3 4 1 2 1 0 9 4]
 [8 0 1 2 8 3 4 3 0 2]
 [3 7 3 7 3 6 2 3 1 1]
 [9 9 5 1 0 8 2 2 0 6]
 [1 6 6 8 1 2 6 4 7 8]
 [8 0 6 1 3 0 5 6 7 2]]
[[0 0 0 0 0]
 [0 9 3 5 3]
 [0 2 8 1 6]
 [0 3 4 2 7]
 [0 2 8 3 6]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [63]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [64]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) 
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [65]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

0


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [66]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[0 0 3]
   [4 2 4]
   [4 3 4]]

  [[0 3 1]
   [2 4 3]
   [3 4 2]]

  [[3 1 4]
   [4 3 3]
   [4 2 1]]

  [[1 4 2]
   [3 3 0]
   [2 1 0]]

  [[4 2 2]
   [3 0 2]
   [1 0 3]]

  [[2 2 0]
   [0 2 1]
   [0 3 4]]

  [[2 0 3]
   [2 1 4]
   [3 4 0]]

  [[0 3 3]
   [1 4 2]
   [4 0 3]]]


 [[[4 2 4]
   [4 3 4]
   [1 4 1]]

  [[2 4 3]
   [3 4 2]
   [4 1 3]]

  [[4 3 3]
   [4 2 1]
   [1 3 1]]

  [[3 3 0]
   [2 1 0]
   [3 1 2]]

  [[3 0 2]
   [1 0 3]
   [1 2 0]]

  [[0 2 1]
   [0 3 4]
   [2 0 3]]

  [[2 1 4]
   [3 4 0]
   [0 3 0]]

  [[1 4 2]
   [4 0 3]
   [3 0 1]]]


 [[[4 3 4]
   [1 4 1]
   [4 3 1]]

  [[3 4 2]
   [4 1 3]
   [3 1 4]]

  [[4 2 1]
   [1 3 1]
   [1 4 3]]

  [[2 1 0]
   [3 1 2]
   [4 3 4]]

  [[1 0 3]
   [1 2 0]
   [3 4 3]]

  [[0 3 4]
   [2 0 3]
   [4 3 2]]

  [[3 4 0]
   [0 3 0]
   [3 2 4]]

  [[4 0 3]
   [3 0 1]
   [2 4 4]]]


 [[[1 4 1]
   [4 3 1]
   [4 4 0]]

  [[4 1 3]
   [3 1 4]
   [4 0 3]]

  [[1 3 1]
   [1 4 3]
   [0 3 2]]

  [[3 1 2]
   [4 3 4]
   [3 2 3]]

  [[1 2 0]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [70]:
class Symetric(np.ndarray):
 def __setitem__(self, index, value):
  i,j = index
  super(Symetric, self).__setitem__((i,j), value)
  super(Symetric, self).__setitem__((j,i), value)
 def symetric(Z):
  return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)
  S = symetric(np.random.randint(0,10,(5,5)))
  S[2,3] = 42
print(S)

[5.08251654 1.3415347  1.15922871 0.98684153 0.96005225 0.87616742
 0.59998427 0.41033981 0.34544314 0.01036136]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [71]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [72]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [73]:
def iterate(Z):
  N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
  Z[1:-1,0:-2] + Z[1:-1,2:] +
  Z[2: ,0:-2] + Z[2: ,1:-1] + Z[2: ,2:])
  birth = (N==3) & (Z[1:-1,1:-1]==0)
  survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
  Z[...] = 0
  Z[1:-1,1:-1][birth | survive] = 1
  return Z
Z = np.random.randint(0,2,(50,50))
for i in range(100):
   Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [74]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9996 9998 9997 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [75]:
def cartesian(arrays):
   arrays = [np.asarray(a) for a in arrays]
   shape = (len(x) for x in arrays)
   ix = np.indices(shape, dtype=int)
   ix = ix.reshape(len(arrays), -1).T
   for n, arr in enumerate(arrays):
       ix[:, n] = arrays[n][ix[:, n]]
       return ix
print(cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]
 [2 0 0]
 [2 0 1]
 [2 1 0]
 [2 1 1]
 [3 0 0]
 [3 0 1]
 [3 1 0]
 [3 1 1]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [76]:
Z = np.array([("Hello", 2.5, 3),
("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
names='col1, col2, col3',
formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [81]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1 loop, best of 5: 3.72 s per loop
10 loops, best of 5: 135 ms per loop
10 loops, best of 5: 117 ms per loop


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [82]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[0 1 2 3 4 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [83]:
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[1 4 1]
 [0 0 1]
 [2 0 3]
 [4 0 2]
 [2 4 2]
 [2 2 4]
 [3 4 4]
 [4 1 3]
 [0 3 1]
 [1 0 1]]
[[1 4 1]
 [0 0 1]
 [2 0 3]
 [4 0 2]
 [2 4 2]
 [2 2 4]
 [3 4 4]
 [4 1 3]
 [0 3 1]
 [1 0 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [84]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [85]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [1 0 0]
 [1 0 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [86]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
np.einsum('i->', A) # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B) # np.inner(A, B)
np.einsum('i,j', A, B) # np.outer(A, B)

array([[3.79471650e-01, 4.18021621e-01, 4.54817985e-01, 7.59775842e-01,
        2.93374951e-01, 2.80760141e-01, 2.38064447e-03, 8.23589783e-02,
        7.72027439e-01, 4.24365197e-01],
       [2.21460099e-01, 2.43957907e-01, 2.65432308e-01, 4.43406071e-01,
        1.71213965e-01, 1.63851947e-01, 1.38934690e-03, 4.80647961e-02,
        4.50556117e-01, 2.47660026e-01],
       [1.30398932e-01, 1.43645969e-01, 1.56290409e-01, 2.61083952e-01,
        1.00813276e-01, 9.64784126e-02, 8.18067688e-04, 2.83012520e-02,
        2.65294004e-01, 1.45825830e-01],
       [3.82511716e-01, 4.21370523e-01, 4.58461674e-01, 7.65862644e-01,
        2.95725270e-01, 2.83009398e-01, 2.39971655e-03, 8.30187819e-02,
        7.78212392e-01, 4.27764919e-01],
       [8.32127644e-02, 9.16662276e-02, 9.97351497e-02, 1.66608094e-01,
        6.43329764e-02, 6.15667269e-02, 5.22041652e-04, 1.80601588e-02,
        1.69294695e-01, 9.30572841e-02],
       [9.45908115e-02, 1.04200154e-01, 1.13372375e-01, 1.89389151e-01,
   

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [87]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)
dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr) 
r_int = np.linspace(0, r.max(), 200)
x_int = np.interp(r_int, r, x) 
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [88]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
[2.0, 0.0, 1.0, 1.0],
[1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [89]:
X = np.random.randn(100) 
N = 1000 
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.20679715  0.18774437]
